#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

max_upload_size=500
ynh_app_setting_set --key=max_upload_size --value=$max_upload_size

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

npm install --global corepack@latest
corepack enable pnpm
corepack use pnpm@latest

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="server.env" --destination="$install_dir/.env"

#=================================================
# SERVER INSTALLATION
#=================================================

pushd "$install_dir/apps/server"
ynh_exec_as_app pnpm install 
ynh_exec_as_app pnpm -r build
pnpm store prune
popd
chown -R $app:$app $install_dir

#=================================================
# CLIENT INSTALLATION
#=================================================

pushd "$install_dir/apps/client"
ynh_exec_as_app pnpm install 
ynh_exec_as_app pnpm -r build
pnpm store prune
popd
chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-server" --template="owlrelay-server.service"


yunohost service add "$app-server" --description="OwlRelay Server" --log="/var/log/$app/$app-server.log"


ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
